# Generated by Django 4.0.3 on 2022-04-19 06:05

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model('Students_crud', 'Student')
    Student(refid="refid1",subject="subject1",description="description1").save()

class Migration(migrations.Migration):

    dependencies = [
        ('Students_crud', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
