# Generated by Django 4.0.3 on 2022-04-28 05:47

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('Students_crud', 'Student')
    Student(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('Students_crud', '0003_alter_student_name'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
