# Generated by Django 4.0.3 on 2022-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_crud', '0005_alter_student_document_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(),
        ),
    ]
